// <auto-generated />
using CodVeda_FullStack_Intern.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodVeda_FullStack_Intern.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260323113942_AddReadUrlToBooks")]
    partial class AddReadUrlToBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodVeda_FullStack_Intern.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("PublishDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReadUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsHidden = false,
                            PublishDate = "1892",
                            Publisher = "George Newnes",
                            ReadUrl = "https://www.gutenberg.org/files/1661/1661-h/1661-h.htm",
                            Summary = "A collection of twelve short stories featuring the legendary detective Sherlock Holmes and his companion Dr. Watson.",
                            Title = "The Adventures of Sherlock Holmes"
                        },
                        new
                        {
                            Id = 2,
                            IsHidden = false,
                            PublishDate = "1865",
                            Publisher = "Macmillan",
                            ReadUrl = "https://www.gutenberg.org/files/11/11-h/11-h.htm",
                            Summary = "A young girl named Alice falls through a rabbit hole into a fantasy world populated by peculiar, anthropomorphic creatures.",
                            Title = "Alice's Adventures in Wonderland"
                        },
                        new
                        {
                            Id = 3,
                            IsHidden = false,
                            PublishDate = "1925",
                            Publisher = "Charles Scribner's Sons",
                            ReadUrl = "https://www.gutenberg.org/cache/epub/64317/pg64317-images.html",
                            Summary = "The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan in the Roaring Twenties.",
                            Title = "The Great Gatsby"
                        });
                });

            modelBuilder.Entity("CodVeda_FullStack_Intern.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            FullName = "System Admin",
                            Password = "&0137Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
